export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_AUTOCOMPLETE = 'UPDATE_AUTOCOMPLETE';
export const UPDATE_DAY_RECORDS = 'UPDATE_DAY_RECORDS';
export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_UI = 'UPDATE_UI';
